import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'Loop Foundry.maxpat');
const patch = JSON.parse(fs.readFileSync(source, 'utf8'));
const engine = patch.patcher.boxes.find(({box}) => box.id === 'engine');
if (!engine || engine.box.maxclass !== 'v8.codebox') throw new Error('Embedded engine box not found');
engine.box.code = fs.readFileSync(path.join(root, 'engine.js'), 'utf8');
const json = JSON.stringify(patch, null, 2);
fs.writeFileSync(source, json);
const payload = Buffer.from(json + '\0', 'utf8');
const header = Buffer.alloc(32);
header.write('ampf', 0); header.writeUInt32LE(4, 4);
header.write('naggmeta', 8); header.writeUInt32LE(4, 16);
header.writeUInt32LE(0, 20); header.write('ptch', 24);
header.writeUInt32LE(payload.length, 28);
fs.writeFileSync(path.join(root, 'Loop Foundry 1.0.amxd'), Buffer.concat([header, payload]));
console.log('Built Loop Foundry 1.0.amxd with its embedded engine.');
